In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs

In [2]:
url = 'https://books.toscrape.com/'
req = requests.get(url)
req.status_code

200

In [3]:
soup = bs(req.content, 'html.parser')
books = soup.select('article')

In [4]:
#Формируется список названий

titles = []

for book in books:
    h3 = book.find('h3')
    title = h3.find('a')['title']
    titles.append(title)

In [5]:
#Формируется список цен

prices = []

for price in books:
    div = price.find('div', attrs={'class':'product_price'})
    number = div.find('p', attrs={'class':'price_color'}).text
    prices.append(float(number[1:]))

In [6]:
#Формируется список рейтингов

ratings = []
words = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}

for rating in books:
    p = rating.find('p')
    ratings.append(p['class'][1])
    
ratings = list(map(words.get, ratings))

In [7]:
#Создание датасета

shop = pd.DataFrame({
    'Title': titles,
    'Rating': ratings,
    'Price': prices
})

shop

                                                Title  Rating  Price
0                                A Light in the Attic       3  51.77
1                                  Tipping the Velvet       1  53.74
2                                          Soumission       1  50.10
3                                       Sharp Objects       4  47.82
4               Sapiens: A Brief History of Humankind       5  54.23
5                                     The Requiem Red       1  22.65
6   The Dirty Little Secrets of Getting Your Dream...       4  33.34
7   The Coming Woman: A Novel Based on the Life of...       3  17.93
8   The Boys in the Boat: Nine Americans and Their...       4  22.60
9                                     The Black Maria       1  52.15
10     Starving Hearts (Triangular Trade Trilogy, #1)       2  13.99
11                              Shakespeare's Sonnets       4  20.66
12                                        Set Me Free       5  17.46
13  Scott Pilgrim's Precious Little Life (Scott Pi...       5  52.29
14                          Rip it Up and Start Again       5  35.02
15  Our Band Could Be Your Life: Scenes from the A...       3  57.25
16                                               Olio       1  23.88
17  Mesaerion: The Best Science Fiction Stories 18...       1  37.59
18                       Libertarianism for Beginners       2  51.33
19                            It's Only the Himalayas       2  45.17